#!/usr/bin/env bash
set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -o noglob # prevent bash from expanding glob
set -o errtrace # inherits trap on ERR in function and subshell
if [[ "${trace:=0}" -eq 1 ]];then
  PS4=' ${LINENO}: '
  set -x
  export trace
fi
trap 'status="$?"; echo "$(basename $0): status:${status} LINENO:${LINENO} BASH_LINENO:${BASH_LINENO} command:${BASH_COMMAND} functions:$(printf " %s" ${FUNCNAME[@]:-})"; exit ${status}' ERR

self="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)/$(basename "$0")"
self_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while getopts "a:h?" options; do case $options in
  a) a="$OPTARG" ;;
  h|?) help; exit ;;
esac; done; shift $((OPTIND - 1))

if [[ "$#" -eq 0 ]];then
  ${0} help

elif [[ "$1" == "help" ]];then shift
  which bash_scripts >/dev/null && bash_scripts show_commands ${0} || true

elif [[ "$1" == "clear" ]];then shift
  docker rm -vf dind1 dind2 dind3 alpine socat prom_socat || true
  docker network rm dind || true

# elif [[ "$1" == "volumes" ]];then shift
#   docker volume create dind1
#   docker volume create dind2

elif [[ "$1" == "setup" ]];then shift
  docker network create --driver=bridge --subnet=10.0.0.0/24 dind
  docker run -d --name dind1 --privileged --network dind docker:18.09-dind
  docker run -d --name dind2 --privileged --network dind docker:18.09-dind
  docker run -d --name dind3 --privileged --network dind docker:18.09-dind
  docker run -t -d --name alpine --network dind alpine /bin/sh

  docker exec -it dind1 /bin/sh -c "\
    docker run -d \
      --network host \
      --name=consul \
      -e CONSUL_BIND_INTERFACE=eth0 \
      consul:1.4.2\
      "

  docker exec -it dind2 /bin/sh -c "\
    docker run -d \
      --name=agent \
      -p 8300:8300 \
      -p 8500:8500 \
      -e 'CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true}' \
      -e SERVICE_IGNORE=true \
      consul:1.4.2 \
      agent -advertise=$(${0} ip dind2) -client=0.0.0.0 -join=$(${0} ip dind1)
      "
      # -p 8300:8300 \
      # -p 8301-8302:8301-8302 \
      # -p 8301-8302:8301-8302/udp \
      # -p 8500:8500 \
      # -p 8600:8600 \

  docker run --name socat -d --network dind -p 8500:8500 alpine /bin/sh -c "\
    apk update;\
    apk add socat; \
    socat TCP-LISTEN:8500,fork TCP:dind1:8500\
    "

  docker exec -it alpine /bin/sh -c 'apk update; apk add curl'

  docker exec -it dind2 /bin/sh -c "\
    docker run -d \
      --name=registrator \
      -v /var/run/docker.sock:/tmp/docker.sock \
      --link agent \
      gliderlabs/registrator:v7 \
      consul://agent:8500\
      "

  docker exec -it dind2 /bin/sh -c "\
    docker run -d \
      -P \
      -e SERVICE_NAME=foo \
      -e SERVICE_TAGS=monitor,bla \
      prom/pushgateway:v0.4.0\
      "

  docker exec -it dind2 /bin/sh -c "\
    docker run -d \
      -P \
      -e SERVICE_NAME=bla \
      -e SERVICE_TAGS=monitor,bla,foo,bar \
      prom/pushgateway:v0.4.0\
      "

  docker exec -it dind3 /bin/sh -c "\
    docker run -d \
      --name=agent \
      -p 8300:8300 \
      -p 8500:8500 \
      -e 'CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true}' \
      -e SERVICE_IGNORE=true \
      consul:1.4.2 \
      agent -advertise=$(${0} ip dind3) -client=0.0.0.0 -join=$(${0} ip dind1)\
      "
  docker exec -it dind3 /bin/sh -c "\
    docker run -d \
      --name=registrator \
      -v /var/run/docker.sock:/tmp/docker.sock \
      --link agent \
      gliderlabs/registrator:v7 \
      consul://agent:8500\
      "

  docker exec -it dind3 /bin/sh -c "\
    docker run -d \
      -P \
      -e SERVICE_NAME=abc \
      -e SERVICE_TAGS=monitor \
      prom/pushgateway:v0.4.0\
      "

  docker cp $(pwd)/prometheus.yml dind3:/root/prometheus.yml
  docker exec -it dind3 /bin/sh -c "\
    docker run -d \
      --name=prometheus \
      -p 9090:9090 \
      --link agent \
      -v /root/prometheus.yml:/etc/prometheus-config/prometheus.yml \
      -e SERVICE_TAGS=monitor \
      prom/prometheus:v2.7.1 \
      --config.file=/etc/prometheus-config/prometheus.yml \
      "
  docker run --name prom_socat -d --network dind -p 9090:9090 alpine /bin/sh -c "\
    apk update;\
    apk add socat; \
    socat TCP-LISTEN:9090,fork TCP:dind3:9090\
    "

elif [[ "$1" == "show" ]];then shift
  echo "consul members:"
  ${0} consul_url agent/members | jq . | jq -c 'map({Addr,role:(.Tags.role)})[]'

  echo "consul services:"
  ${0} consul_url catalog/services | jq . | jq -c 'to_entries[]'

  echo "prometheus targets:"
  curl -s "http://localhost:9090/api/v1/targets" | jq -c '.data.activeTargets|map(.labels)[]'

elif [[ "$1" == "consul_url" ]];then shift
  url="$1"; shift
  docker exec -it alpine /bin/sh -c "curl http://$(${0} ip dind1):8500/v1/${url}"

elif [[ "$1" == "alpine_curl" ]];then shift
  url="$1"; shift
  docker exec -it alpine /bin/sh -c "curl -i -s http://${url}"

elif [[ "$1" == "ip" ]];then shift
  container="$1"; shift
  docker inspect ${container} | jq -r 'map(.NetworkSettings.Networks.dind.IPAddress)[]'

elif [[ "$1" == "network" ]];then shift
  docker network inspect dind | jq 'map(.Containers|map({Name,IPv4Address}))[]'

else
  echo "unknown command: $@" >&2
  exit 1
fi

